### ISSUE TITLE
Not an overlay - Chrome

### ISSUE THREAD

**Issue by sjudenim** [StylishThemes/Overlay-Scrollbars#5]
Just to be clear, this scrollbar does not overlay the content of web pages. It creates a track to the side which uses the body background colour.

I've struggled to find a way to create a true overlay in Chrome the way you can in Firefox. The odd thing is that internal pages for Vivaldi can have an overlay but web pages won't when using the same code and it makes no difference with the flag enabled or not.

**Comment by silverwind** [comment]
They aren't really overlay in Firefox either, the scrollbar track does not show `background-image`, thought that could as well be a Firefox bug.

I think the only proper overlay version was the variant that targeted Firefox's XUL scollbars, but that API no longer exists for extensions since Firefox 57.

**Comment by sjudenim** [comment]
I guess that's around the time I stopped using it in favour of Vivaldi. So I should have said, could rather than can.

**Comment by the-j0k3r** [comment]
Something to probably add to the readme.md though its just a name.
